### PR TITLE
Added Caps Lock --> Spotlight Search function.

### PR DESCRIPTION
**Pull request by JackSalzman**
Added CapsLocktoSearch.json and updated groups.json with changes.

### CODE REVIEW

**Comment by JackSalzman** [comment]
This is my first pull request on GitHub. I added a modification that remaps the ⇪ key to ⌘ + ␣.

Also, did you know? You can insert OS symbols (⌘⎋⏏︎⇪⇧⌤⌥⎇␣⌅⌦⌧⌫) by pressing fn+E and scrolling to the bottom.

**Comment by JackSalzman** [comment]
Added complex modification "Command Delete to Command Backspace"

**Comment by tekezo** [comment]
Thanks!

You can also use "spotlight" key instead of command+spacebar.
The spotlight key always activates the spotlight, independent of the macOS shortcut settings.
(It can also be pressed together with the option key to open the settings.)

```json
    "to_if_held_down": [
        {
            "apple_vendor_keyboard_key_code": "spotlight"
        }
    ]
```

**Comment by JackSalzman** [comment]
> Thanks!
> 
> You can also use "spotlight" key instead of command+spacebar. The spotlight key always activates the spotlight, independent of the macOS shortcut settings. (It can also be pressed together with the option key to open the settings.)
> 
> ```json
>     "to_if_held_down": [
>         {
>             "apple_vendor_keyboard_key_code": "spotlight"
>         }
>     ]
> ```

some older Macs do not support the spotlight key, but I agree that your way is a more efficient way of writing it.

**Pull request merged**
