### PR TITLE
Add Ctrl-k for Microsoft Office in emacs_key_bindings

### PR DESCRIPTION
**Pull request by hnakamur**
This maps Ctrl-k to Shift+End, Delete.

### CODE REVIEW

**Comment by tekezo** [comment]
Can you also update `src/json/emacs_key_bindings.json.rb`?

**Comment by hnakamur** [comment]
Thanks for your comment.
I updated `src/json/emacs_key_bindings.json.rb` and ran `./scripts/update-json.sh`.

**Review by tekezo — APPROVED** [review]
LGTM!

**Comment by tekezo** [comment]
I also update revisions of emacs key bindings:
https://github.com/pqrs-org/KE-complex_modifications/pull/1328

**Comment by hnakamur** [comment]
Thanks!

**Pull request merged**
