### PR TITLE
Update media key only control itunes - add f7, f9 key

### PR DESCRIPTION
**Pull request by casamia918**

### CODE REVIEW

**Comment by tekezo** [comment]
Thanks!
You can update your json files without review :-)

**Comment by casamia918** [comment]
Ok, I got it. thanks.

**Comment by casamia918** [comment]
Um... complex modification repository web site (https://pqrs.org/osx/karabiner/complex_modifications/) is not showing new rule of this commit. 
Is there something problem? At my computer, f7 and f9 is working well.

**Comment by tekezo** [comment]
Thank you for feedback!

The update issue caused by including `docs/dist.json` to repository.
I removed it ( https://github.com/pqrs-org/KE-complex_modifications/commit/024255682775a4147df33a2f4c305cff574dda63 ), and then pqrs.org works fine.

**Comment by casamia918** [comment]
Thanks. But hm.. Sth strange.

I've follow the publishing guide of readme. At the guide, it says that to publish, commit docs/dist.json to repository. So, I've edit .gitignore (remove docs/dist.json pattern) and include docs/dist.json in my commit. (But not include .gitignore. Actually, I feel quite awkward while doing this). I don't know what did I mistake. You'd better modify guide message of readme file.



> README.md
> 
> **Publish your own forked page**
> If you want to publish your own forked page, please commit docs/dist.json to repository. (dist.json will be generated by make command)
> 
> The dist.json is ignored by .gitignore in order to avoid file conflicting because the file is editted by multiple users in the main repository.

**Comment by tekezo** [comment]
Thank you for pointing out!

I updated README.
https://github.com/pqrs-org/KE-complex_modifications#publish-your-own-forked-page

**Pull request merged**
