### PR TITLE
Create Paste and Match Style - Windows

### PR DESCRIPTION
**Pull request by blckout99**
Use Control + Shift + V to paste clipboard with matching style to document.

### CODE REVIEW

**Comment by tekezo** [comment]
Please remote whitespaces from file name.

**Comment by blckout99** [comment]
tekezo, yes of course... How? Do I resubmit it again, or can I edit the submitted one already? I'm not seeing anywhere to edit it at. I'm sorry, thank you!

**Comment by blckout99** [comment]
Okay. I think I got it. I'm waiting for the build check to finish again.

**Comment by blckout99** [comment]
tekezo, no it failed the check again. I'm sorry. Do you know what I am missing?

**Comment by blckout99** [comment]
Okay... All PASSED.. Woohoo. Now what?

**Comment by tekezo** [comment]
Thanks!
The merge is not performed automatically since it is a manual operation 👍

**Pull request merged**
