### PR TITLE
Update windows_shortcuts_on_macos.json

### PR DESCRIPTION
**Pull request by MrTantum**
Fixed incorrect setting for command Ctrl+Y => Cmd+Shift+Y (Redo):
- Changed z to y.
- Left shift modifier removed.

### CODE REVIEW

**Comment by tekezo** [comment]
@MrTantum 
Oops, I think this is incorrect in the description, usually redo is command+shift+Z.
https://support.apple.com/guide/pages/undo-or-redo-changes-tana7e101d4c/mac

So, I think `to` content is not needed to change.
Is `command+y` redo in your environment?

**Comment by MrTantum** [comment]
Yep you are right seems to be a special case of german QUERTZ Kezboard layout:

_If I use German layout, the Undo shortcut (Ctrl-Z) is binded to the key Z, which is located in the middle of the first letter row between T and U. The Redo (Ctrl-Y) is binded to the key Y, which is located left to X in the low row of letters on the German QWERTZ layout._ [Source](https://superuser.com/q/1246573)

But still something is odd about those settings here in Carabiner Elements or why are both commands mapping to Z key?

```
{
    "description": "Ctrl+Z => Cmd+Z (Undo)",
    "manipulators": [
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "^com\\.microsoft\\.rdc$",
                        "^com\\.microsoft\\.rdc\\.mac$",
                        "^com\\.microsoft\\.rdc\\.macos$",
                        "^com\\.microsoft\\.rdc\\.osx\\.beta$",
                        "^net\\.sf\\.cord$",
                        "^com\\.thinomenon\\.RemoteDesktopConnection$",
                        "^com\\.itap-mobile\\.qmote$",
                        "^com\\.nulana\\.remotixmac$",
                        "^com\\.p5sys\\.jump\\.mac\\.viewer$",
                        "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$",
                        "^com\\.teamviewer\\.TeamViewer$",
                        "^com\\.vmware\\.horizon$",
                        "^com\\.2X\\.Client\\.Mac$",
                        "^com\\.vmware\\.fusion$",
                        "^com\\.vmware\\.horizon$",
                        "^com\\.vmware\\.view$",
                        "^com\\.parallels\\.desktop$",
                        "^com\\.parallels\\.vm$",
                        "^com\\.parallels\\.desktop\\.console$",
                        "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                        "^com\\.citrix\\.XenAppViewer$",
                        "^com\\.vmware\\.proxyApp\\.",
                        "^com\\.parallels\\.winapp\\.",
                        "^org\\.macports\\.X11$",
                        "^com\\.apple\\.Terminal$",
                        "^com\\.googlecode\\.iterm2$",
                        "^co\\.zeit\\.hyperterm$",
                        "^co\\.zeit\\.hyper$",
                        "^io\\.alacritty$",
                        "^net\\.kovidgoyal\\.kitty$",
                        "^tv\\.parsec\\.www$"
                    ],
                    "type": "frontmost_application_unless"
                }
            ],
            "from": {
                "key_code": "z",
                "modifiers": {
                    "mandatory": [
                        "control"
                    ],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "z",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
},
{
    "description": "Ctrl+Y => Cmd+Shift+Y (Redo)",
    "manipulators": [
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "^com\\.microsoft\\.rdc$",
                        "^com\\.microsoft\\.rdc\\.mac$",
                        "^com\\.microsoft\\.rdc\\.macos$",
                        "^com\\.microsoft\\.rdc\\.osx\\.beta$",
                        "^net\\.sf\\.cord$",
                        "^com\\.thinomenon\\.RemoteDesktopConnection$",
                        "^com\\.itap-mobile\\.qmote$",
                        "^com\\.nulana\\.remotixmac$",
                        "^com\\.p5sys\\.jump\\.mac\\.viewer$",
                        "^com\\.p5sys\\.jump\\.mac\\.viewer\\.web$",
                        "^com\\.teamviewer\\.TeamViewer$",
                        "^com\\.vmware\\.horizon$",
                        "^com\\.2X\\.Client\\.Mac$",
                        "^com\\.vmware\\.fusion$",
                        "^com\\.vmware\\.horizon$",
                        "^com\\.vmware\\.view$",
                        "^com\\.parallels\\.desktop$",
                        "^com\\.parallels\\.vm$",
                        "^com\\.parallels\\.desktop\\.console$",
                        "^org\\.virtualbox\\.app\\.VirtualBoxVM$",
                        "^com\\.citrix\\.XenAppViewer$",
                        "^com\\.vmware\\.proxyApp\\.",
                        "^com\\.parallels\\.winapp\\.",
                        "^org\\.macports\\.X11$",
                        "^com\\.apple\\.Terminal$",
                        "^com\\.googlecode\\.iterm2$",
                        "^co\\.zeit\\.hyperterm$",
                        "^co\\.zeit\\.hyper$",
                        "^io\\.alacritty$",
                        "^net\\.kovidgoyal\\.kitty$",
                        "^tv\\.parsec\\.www$"
                    ],
                    "type": "frontmost_application_unless"
                }
            ],
            "from": {
                "key_code": "y",
                "modifiers": {
                    "mandatory": [
                        "control"
                    ],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "z",
                    "key_code": "y",
                    "modifiers": [
                        "left_command",
                        "left_shift""left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by tekezo** [comment]
Thank you for information.
I updated the rules to change key_code when the current input source is German using input_source_if.
https://github.com/pqrs-org/KE-complex_modifications/pull/1458/commits/81b3000e894878f65dc03c87a38017df16206e69

Please confirm the latest undo and redo configuration!
https://ke-complex-modifications.pqrs.org/#windows_shortcuts_on_macos

**Comment by MrTantum** [comment]
Thanks confirmed from my side.

**Comment by tekezo** [comment]
Thanks!

**Pull request merged**
