### PR TITLE
[JIS] "Shift+2" to "@"

### PR DESCRIPTION
**Pull request by spookyway**
Title says all

### CODE REVIEW

**Comment by spookyway** [comment]
Thank you for your feedback. Later I'd update this project by changing other JIS elements to corresponding ISO ones as far as possible.

**Comment by tekezo** [comment]
Does not this configuration help you?

**Comment by spookyway** [comment]
It does, but partly. "¥" and "_" keys do nothing under the virtual keyboard layout. Some keys are missing as well. Now I'm using "kana" key as tilda . . . but the layout can be improved in more effective way.

**Comment by tekezo** [comment]
OK, please fill the keys which is not possible by keyboard type.

Note:
I recommend you to use simple_modifications if keys can be simply exchanged to avoid conflict another complex_modifications rules.
Karabiner-Elements applies only one complex_modifications for one event.
If you use complex_modifications to layout changes, other complex_modifications rules (e.g., emacs key bindings) will be ignored for the keys.

**Comment by tekezo** [comment]
I close this PR for now.
Please make new PR when you made a complete definition.

**Pull request closed without merging**
