### PR TITLE
Add German Characters (Umlauts and Eszett) with Caps Lock

### PR DESCRIPTION
**Pull request by justinmcbride**
Add a new Complex Modification that hosts a set of different rules.
Use the Caps Lock key as a modifier key, but for getting access to the German letters. Easy access to äöü, ÄÖÜ, and ß.

### CODE REVIEW

**Comment by MuhammedZakir** [comment]
It maybe better to specify which type of keyboard layout is needed for this to work.

**Comment by justinmcbride** [comment]
> It maybe better to specify which type of keyboard layout is needed for this to work.

Thanks for the suggestion. Can you provide guidance on how you propose I do this? Simply inside the extended info?

**Comment by MuhammedZakir** [comment]
1. Yes, explain that in the extended info.
2. Optional, but recommended: if you can restrict the manipulators to certain layouts (e.g. German language?) [1] or certain keyboard types (e.g. ISO) [2], then do so. Don't need to language restriction if you want to and can use those in other keyboard layouts.
    - The reason for this is to prevent conflicts when you have or imported many rules.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/input-source/
[2] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/keyboard-type/

**Comment by justinmcbride** [comment]
> 1. Yes, explain that in the extended info.
Went ahead and added that info.

> 2. Optional, but recommended: if you can restrict the manipulators to certain layouts (e.g. German language?) [1] or certain keyboard types (e.g. ISO) [2], then do so. Don't need to language restriction if you want to and can use those in other keyboard layouts.

I added those restrictions.

**Comment by MuhammedZakir** [comment]
Merged. :-)

**Pull request merged**
