### PR TITLE
Extension to the media buttons swap, added docu

### PR DESCRIPTION
**Pull request by Jendker**
Added new functions to make the configuration of the swap media with f keys faster

### CODE REVIEW

**Comment by ajdajd** [comment]
Using Option 3 (inversion) with unchecked box and default Function Keys assignment (f1 = display_brightness_decrement).

The profiles that have this inverts the checkbox as expected. But for some reason, Apple Internal Keyboard has to be unchecked in the Devices tab. I am purely testing on my MacBook Pro's built-in keyboard.

**Comment by Jendker** [comment]
Thanks for your report!

Could you tell me what do you exactly observe? Because Karabiner itself messes a bit f keys (e.g. https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000087984-Shift-F6-rename-or-Shift-F-is-invalid)

**Comment by ajdajd** [comment]
Please disregard what I reported earlier. It's working as intended.

My settings:

- Checked box
- Default Function Keys assignment (f1 = display_brightness_decrement)

Profile 1 (f1 = brightness control): no Complex Modification
Profile 2 (f1 = f1): has Complex Modification

I apologize for the confusion. Disregard this statement:

>  But for some reason, Apple Internal Keyboard has to be unchecked in the Devices tab.

**Comment by apm1467** [comment]
Thanks!

**Pull request merged**
