### PR TITLE
Neo2 layer3 fixes

### PR DESCRIPTION
**Pull request by andre-krueger**
~~These changes require that [this](https://git.neo-layout.org/neo/neo-layout/pulls/644) pull request is merged first.~~

### CODE REVIEW

**Comment by tekezo** [comment]
OK, please remove the WIP when ready.

**Comment by andre-krueger** [comment]
The PR is ready for review.

**Comment by Cu3PO42** [comment]
I have just created another PR (#1594) which will have merge conflicts with this one. They are trivially resolveable, however. (I have just added another Terminal application to the list of excluded apps for the 'prevent option key shortcut' rules.)

I'm not sure which is the best way to go forward, but I'd also be happy to have you include that change in your PR as well.

**Review by tekezo — APPROVED** [review]
@andre-krueger 
Sorry, I missed your comment about the preparations being complete.
LGTM, Thanks!

**Pull request merged**
