### PR TITLE
added virtual numeric keypad using Tab

### PR DESCRIPTION
**Pull request by kamykaze**
Added a virtual numeric keypad by holding Tab. This is useful if you are typing numbers and don't have a full keyboard.

### CODE REVIEW

**Comment by apm1467** [comment]
This may conflict with the Vi Mode. Control + Fn + J/K/L are defined as arrow keys in Vi Mode, but number keys in this rule. So they will basically overwrite each other.

Would you consider using something like Option + Fn instead of Control + Fn as modifier keys in this rule?

**Comment by tekezo** [comment]
Thanks!

**Comment by kamykaze** [comment]
@apm1467 You're right. I copied the vi mode file to start this, which is why the modifier keys are the same. I don't care for the modifier keys Option + Fn because ultimately I'm using Tab. But it seems a combination of modifier is needed in order to make Tab work as Tab if nothing else is pressed. 

I'll have to do more testing to see if I can achieve the same without any Ctrl/Opt/Fn modifiers, but I'll change it to Control + Fn if that doesn't work.

**Comment by apm1467** [comment]
Yes, the Vi Mode is kind of a hack. Since the S key (or in this rule, the Tab key) is not a modifier key, it can not build a key combination with another non-modifier key.

So the Vi Mode changes the S key into a "fake" modifier Control + Fn, which is a modifier that almost no one is using, so it can build valid key combinations with other keys, and won't cause conflict with normal modifier keys usage.

What your rule could do, is to choose another rarely used "fake" modifier, so it will not cause conflict with normal usage. 

I do want to see if this can be achieved without such kind of hacking. Good luck with testing.

**Pull request merged**
