### PR TITLE
Add Mu Mode Semicolon(;)+J/K/L/I/U/M/O/. to Arrow Left/Down/Right/Up/PageUp/PageDown/Home/End

### PR DESCRIPTION
**Pull request by muyinliu**
Mu Mode Semicolon(;)+J/K/L/I/U/M/O/. to Arrow Left/Down/Right/Up/PageUp/PageDown/Home/End

Note: with only right hand also can press Arrow keys(on HHKB it's great!).

### CODE REVIEW

**Comment by kamykaze** [comment]
Did you write the json file from scratch? I think preferably we want the file to be generated from its .erb file. That makes the original file simpler and easier to maintain.

**Comment by smlewis** [comment]
@kamykaze Just to note - the README suggests that writing the JSON directly into docs/json is ok (first line under 'Add Rules') - if it's not OK then perhaps the README should say so?  (I don't know what the maintainers want the rule to be, I'm just commenting on the discrepancy, as a mostly-clueless user)

**Comment by tekezo** [comment]
Thanks!

**Comment by muyinliu** [comment]
@tekezo How long will this config show on page [Karabiner-Elements complex_modifications rules](https://pqrs.org/osx/karabiner/complex_modifications/) after merged?

**Comment by muyinliu** [comment]
@kamykaze thanks.

**Pull request merged**
