### PR TITLE
Map fn+numbers to corresponding function keys

### PR DESCRIPTION
**Pull request by bingocaller**
This solves [#847](https://github.com/tekezo/Karabiner-Elements/issues/847) in a pretty straightforward manner.

### CODE REVIEW

**Comment by tekezo** [comment]
Thanks!

**Comment by bingocaller** [comment]
@tekezo No problem! This should work, right?
[It's not working for @dluxhu as is](https://github.com/tekezo/Karabiner-Elements/issues/847), but I can't figure out why? Right now I can't get _any_ Modifications to work on my machine; neither simple nor complex ones.

**Comment by kamykaze** [comment]
I tested this. It mostly works. One thing I had to make sure is to check the "Use all F1, F2, etc. keys as standard function keys" option under the Function keys tab of Karabiner. Otherwise you get those hardware keys for Display brightness, etc.

There is one bug though: F11 and F12 don't work. This is because you have "-" and "=" as the key code. It should be "hyphen" and "equal_sign"

**Comment by bingocaller** [comment]
@kamykaze Haha, whoopsie! 😅
I actually have another commit in the pipeline which uses the `_each_key` method to generate the JSON for all the remappings; now I can get the correct key names in there. Maybe also a note in the description regarding "Use all F1, F2…"?
Anyways, thanks for testing this for me. I still haven't been able to make Modifications work on my machine. 😕

**Comment by kamykaze** [comment]
yeah, those changes would be nice. I hope you get your mappings working. Any idea what's wrong? Maybe create an issue here in KE repo?

**Comment by bingocaller** [comment]
I don't have a clue what's wrong with my mappings. I've tried a few things already, but I think I'll create an issue to track it there.

**Comment by bingocaller** [comment]
Hmm.. I just updated to v0.91.12 and now everything is working fine! 😌

**Pull request merged**
