### PR TITLE
Vim Mode Plus with Better Notifications

### PR DESCRIPTION
**Pull request by gilitos92**
A fork of the "Vim Mode Plus" modification by @harmtemolder that only modifies the way notifications work.

### CODE REVIEW

**Comment by tekezo** [comment]
Thanks!

**Comment by harmtemolder** [comment]
@gilitos92 If you want you can take over my "Vim Mode Plus" mod completely. I don't use macOS or Karabiner-Elements any more, so am not maintaining it...

**Comment by gilitos92** [comment]
@harmtemolder Thank you for the trust and making the original script. I think it is better to leave them as separate Modifications because some people might prefer having the non-persistent notifications.

**Comment by Din0Git** [comment]
Thanks for the script. Is there a way to change the placement for the notification? An offset of some sort? 

Greetz Dino

**Pull request merged**
