### PR TITLE
minila_application_to_fn4

### PR DESCRIPTION
**Pull request by hisanshao**
minila_application_to_fn4.json

### CODE REVIEW

**Comment by apm1467** [comment]
Thank you for your commits. I'm just curious: what does fn+4 do?

**Comment by hisanshao** [comment]
I bought a pair of mechanical keyboards(filco minila)。I want to change app key to fn+4(launchpad). So i can add some rules in karabiner-element(mac application). the rules file is in my github repositories. (https://github.com/hisanshao/complex_modifications/blob/master/minila_application_to_fn4.json).

[https://avatars3.githubusercontent.com/u/26359618?s=400&v=4]<https://github.com/hisanshao/complex_modifications/blob/master/minila_application_to_fn4.json>

hisanshao/complex_modifications<https://github.com/hisanshao/complex_modifications/blob/master/minila_application_to_fn4.json>
github.com
~/.config/karabiner/assets/complex_modifications




________________________________
发件人: Yi Ge <notifications@github.com>
发送时间: 2018年5月25日 22:45
收件人: pqrs-org/KE-complex_modifications
抄送: hisanshao; Author
主题: Re: [pqrs-org/KE-complex_modifications] minila_application_to_fn4 (#369)


Thank you for your commits. I'm just curious: what does fn+4 do?

―

**Comment by apm1467** [comment]
In that case, fn+f4 is launchpad. Is that what you intended to do? As I know, fn+4 does nothing.

**Comment by hisanshao** [comment]
this keyboards(filco minila) has only 67keys, there is no f4 keys. lt is only number keys. so i can use launchpad through set fn+4 in karabiner

wangke

在 2018年5月26日，10:20，Yi Ge <notifications@github.com<mailto:notifications@github.com>> 写道：


In that case, fn+f4 is launchpad. Is that what you intended to do? As I know, fn+4 does nothing.

**Comment by hisanshao** [comment]
this is my keyboard[cid:69883859-f510-44b8-80f7-d022392cd64d]
[cid:b598d681-a9b1-49fe-bc5e-89710a6218aa]


________________________________
发件人: Yi Ge <notifications@github.com>
发送时间: 2018年5月26日 10:20
收件人: pqrs-org/KE-complex_modifications
抄送: hisanshao; Author
主题: Re: [pqrs-org/KE-complex_modifications] minila_application_to_fn4 (#369)


In that case, fn+f4 is launchpad. Is that what you intended to do? As I know, fn+4 does nothing.

―

**Comment by apm1467** [comment]
Even if there's no f1 - f12 keys on your keyboard, you can still map to them in Karabiner-Elements. These key codes are always available in Karabiner-Elements, independent from your keyboard.

The "system fn key" and the fn key on your keyboard is not the same fn key. If you are using a keyboard made by Apple, these two keys are the same; but for third party keyboards, usually the "system fn key" is not on the keyboard. You can verify this in Karabiner-EventViewer (which is installed automatically when you install Karabiner-Elements). The system will recognize nothing when you press fn on your third party keyboard.

So if you want f4, just map to f4 in Karabiner-Elements directly. Map to fn+4 will have the effect of pressing fn+4 on a keyboard made by Apple.

Also a quick note: If you just want to add rules, you can directly copy the JSON rule files to `~/.config/karabiner/assets/complex_modifications/` on your computer. You will then see them in Karabiner-Elements app. We welcome you to contribute to this official repository, but it is not necessary to push here if you just want to add rules on your own computer. Actually, I encourage you to test the rules on your computer locally first before pushing them here.

**Comment by hisanshao** [comment]
I am so sorry to tell you that i made a mistake.I lost my another mailbox password too many times a few days ago. I used this mailbox to get the password back.I thought it was the outlook so that I could return to some questions to retrieve the password.I didn't look at the sender carefully.I'm very sorry to disturb you. and yes, my json file is wrong. but I've solved the key problem of the keyboard through karabiner-element(very useful). Thank you for answering my questions so patiently


________________________________
发件人: Yi Ge <notifications@github.com>
发送时间: 2018年5月26日 20:11
收件人: pqrs-org/KE-complex_modifications
抄送: hisanshao; Author
主题: Re: [pqrs-org/KE-complex_modifications] minila_application_to_fn4 (#369)


Even if there's no f1 - f12 keys on your keyboard, you can still map to them in Karabiner-Elements. These key codes are always available in Karabiner-Elements, independent from your keyboard.

The "system fn key" and the fn key on your keyboard is not the same fn key. If you are using a keyboard made by Apple, these two keys are the same; but for third party keyboards, usually the "system fn key" is not on the keyboard. You can verify this in Karabiner-EventViewer (which is installed automatically when you install Karabiner-Elements). The system will recognize nothing when you press fn on your third party keyboard.

So if you want f4, just map to f4 in Karabiner-Elements directly. Map to fn+4 will have the effect of pressing fn+4 on a keyboard made by Apple.

Also a quick note: If you just want to add rules, you can directly copy the JSON rule files to ~/.config/karabiner/assets/complex_modifications/ on your computer. You will then see them in Karabiner-Elements app. We welcome you to contribute to this official repository, but it is not necessary to push here if you just want to add rules on your own computer. Actually, I encourage you to test the rules on your computer locally first before pushing them here.

―

**Pull request closed without merging**
