### PR TITLE
Add PC style word navigation rules

### PR DESCRIPTION
**Pull request by mbaker3**
Users who want to have PC style selection likely also want PC style navigation.

### CODE REVIEW

**Comment by MuhammedZakir** [comment]
I think we need to duplicate all manipulators, but without `shift` in modifiers, to get all navigations. What do you think?

**Comment by mbaker3** [comment]
I'm not sure what the intention for the original up/down mappings was. I don't use those shortcuts and a quick test in Notepad on Windows revealed that `Ctrl+Shift+Up/Down` and `Ctrl+Up/Down` don't appear to do anything.
In Chrome the key combination is no different than pressing `Shift+Up/Down` or `Up/Down`

Do you know what the expected behaviour for `Ctrl+Shift+Up` and `Ctrl+Shift+Down` is in Windows?

I'm happy to setup mappings if I know what behaviour I'm trying to emulate!

**Comment by MuhammedZakir** [comment]
I can't test them as I don't use Windows. But, even if they don't work in Windows, IMHO, if shortucts work in macOS, then we should just leave them as is. Although this may go against "_PC style_ word navigation".

**Comment by MuhammedZakir** [comment]
So what should we do about this:

> I think we need to duplicate all manipulators, but without shift in modifiers, to get all navigations. What do you think?

If you are against this, I can merge your PR as is.

**Comment by mbaker3** [comment]
Based on our discussion I don't think it makes sense to duplicate all manipulators without the shift modifiers.

**Reason:** Windows users don't expect any behaviour for that key combination.

**Comment by mbaker3** [comment]
Just noticed the original title had a typo in it. Added the fix to this PR.

**Comment by MuhammedZakir** [comment]
Thanks! :-)

**Pull request merged**
