### PR TITLE
Add Mu Mouse Mode

### PR DESCRIPTION
**Pull request by muyinliu**
`Semicolon(;)+D` to enter **Mu Mouse Mode**(default **Mouse Move Mode**); 
`V` to Mouse Left Click; 
`N` to Mouse Right Click; 
`Q` to quit **Mu Mouse Mode**; 
`D` to **Mouse Move Mode**, 
`J`/`K`/`L`/`I`/`U`/`M`/`O`/`.` to Mouse `Left`/`Down`/`Right`/`Up`/`Up-Left`/`Down-Left`/`Up-Right`/`Down-Right`; 
`F` to **Mouse Fast Move Mode**, like Mouse Move Mode but **faster**; 
`S` to **Mouse Scroll Mode**, `J`/`K`/`L`/`I` to Mouse Scroll Left/Down/Right/Up

### CODE REVIEW

**Comment by MuhammedZakir** [comment]
Can you please`terminal-notifier` to `osascript`? [1] As these are meant to be installed by others, try not to use external programs unless the complex modification *absolutely* need it.

[1] https://github.com/pqrs-org/KE-complex_modifications/search?q=osascript

---

Do you use `fn` with any of those combinations? Is that why you are listing all modifiers except `fn`? If you don't, why not| use `any` in `from.modifiers.optional`?

**Comment by MuhammedZakir** [comment]
@tekezo : Shall I fix this myself?

**Comment by muyinliu** [comment]
Sorry for the delay. I will fix it soon. Thanks~

**Comment by muyinliu** [comment]
Done!

Note: Sorry for the delay, again.

**Comment by MuhammedZakir** [comment]
Maybe you forgot to push a commit? "terminal-notifier" is not replaced with "osascript".

> Can you please change`terminal-notifier` to `osascript` for notifications? [1] As these configurations are meant to be installed by others, try not to use external programs unless the complex modification _absolutely_ need it.
> 
> [1] https://github.com/pqrs-org/KE-complex_modifications/search?q=osascript

**Comment by muyinliu** [comment]
> Maybe you forgot to push a commit? "terminal-notifier" is not replaced with "osascript".
> 
> > Can you please change`terminal-notifier` to `osascript` for notifications? [1] As these configurations are meant to be installed by others, try not to use external programs unless the complex modification _absolutely_ need it.
> > [1] https://github.com/pqrs-org/KE-complex_modifications/search?q=osascript
> 
> Edit:
> 
> > Note: Sorry for the delay, again.
> 
> It's alright. Take your time! :-)

Done. Replaced `terminal-notifier` with `osascript -e 'display notification xxx'`.

Thank you for the reminder.

**Pull request merged**
